.vscode/launch.json
.vscode/tasks.json
README.md
appveyor.yml
build.cake
build/util.cake
src/Athena.Core/Athena.Core.csproj
src/Athena.Data/Athena.Data.csproj
src/Athena/Athena.csproj
test/Integration/Athena.Data.Tests/Athena.Data.Tests.csproj

Now that we're writing some tests we should track code coverage. Note that these reports are only generated on windows, the coverage tool does not support linux yet.
Stats are visible here: https://codecov.io/gh/athena-scheduler/athena. Note that while codacy supports code coverage (and I'd rather use a unified tool), it doesn't support `.net` coverage reports yet so we'd have to write our own importer.
If I did it right a bot should also comment on the PR like codacy.

Use codecov for coverage

---

src/Athena.Data/Migrations/20180215110432_Identity.cs

a515e90 introduced a change to use the role store for adding the default administrator user. Because our migration framework does not support async migrations, we manually call `.GetAwaiter().GetResult()`. It appears that this pattern **may** deadlock in certain use cases. By wrapping the async call in a `Task.Run(...).GetAwaiter().GetResult()` we can avoid this deadlock.
This is just a hotfix to get us up and running right now (Fixes #18). We should consider `.ConfigureAwait(false)` where applicable to avoid this in other places (although as far as I know the only place where we are calling async code from a sync context is in migrations, and even then this is the only instance).
If we add more migrations that need to call async methods, we should wrap this in an `AsyncMigration` to make …

Avoid deadlocks on identity migrations (See #18)

---

src/Athena.Data/Migrations/20180215110432_Identity.cs
src/Athena/Athena.csproj
src/Athena/Views/Shared/_Nav.cshtml
src/Athena/Views/_ViewImports.cshtml

Adds support for profile images via [gravatar](https://en.gravatar.com/)
Users who do not have an image set will see a random robot:

Add support for gravatar

---

.travis.yml
appveyor.yml

Use the [Build Cache](https://www.appveyor.com/docs/build-cache/) on appveyor and the [Cache](https://docs.travis-ci.com/user/caching/) on travis to try to speed up builds. Linux isn't too bad but appveyor builds are painfully slow.

Speed up builds by caching node_modules

---

build/util.cake

This fixes coverage results so when we start testing the main Athena assembly coverage is properly counted.

Include coverage for main athena assembly

---

.travis.yml
Dockerfile
build.cake
build/travis.sh
contrib/wait-postgres.sh
docker-compose.yml
tools/packages.config

This adds tasks for generating a docker image which will automatically be pushed to the docker hub on master from travis-ci. I also added a docker-compose script, if you want to test it out, install [`docker-compose`](https://docs.docker.com/compose/install/) and do the following:
```bash
./build.sh -t Dist # or on windows: ./build.ps1 -t Dist
docker-compose up
```

Add support for docker and docker-compose

---

.gitignore
build.cake
build/util.cake
minicover/minicover.csproj
src/Athena.Core.Validation/Athena.Core.Validation.csproj
src/Athena.Core/Athena.Core.csproj
src/Athena.Data/Athena.Data.csproj
src/Athena/Athena.csproj
test/Integration/Athena.Data.Tests/Athena.Data.Tests.csproj

This enables code coverage on non-windows platforms and is still compatible with CodeCov. The metrics are a tad different since I don't think it includes branches, but for our use cases I think that is acceptable. Here's a preview of what you'll see if you use the build script:

Use Minicover instead of OpenCover

---

src/Athena.Data/Migrations/20180322190011_DropDuplicateLinks.cs
src/Athena.Data/Migrations/src/20180322190011_DropDuplicateLinks.sql
src/Athena.Data/Repositories/CampusRepository.cs
src/Athena.Data/Repositories/CourseRepository.cs
src/Athena.Data/Repositories/InstitutionRepository.cs
src/Athena.Data/Repositories/ProgramRepository.cs
src/Athena.Data/Repositories/StudentRepository.cs
test/Integration/Athena.Data.Tests/Repositories/CampusRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/InstitutionRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/OfferingRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/ProgramRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/StudentRepositoryTests.cs

Previously, it was possible to insert duplicate rows into relationship tables. For example, a student could register for an institution multiple times and duplicate results would be shown when queried via the API. This PR does two things:
* Add a migration to drop any duplicate entries and add a unique constraint to prevent further duplicate entries
* Check for duplicate insertion at the API and throw `DuplicateObjectException` if attempted.
Fixes #47

Do not allow duplicate entries in relationship tables

---

src/Athena.Data/EnvironmentVariableConnectionStringProvider.cs
src/Athena.Data/Extensions/ServiceCollectionExtensions.cs
src/Athena.Data/IConnectionStringProvider.cs
src/Athena/Athena.csproj
src/Athena/Setup/ApplicationBuilderExtensions.cs
src/Athena/Setup/Program.cs

We need to ensure the database is ready before we can run migrations or accept any requests. This makes the web host more graceful to stand up in a docker-compose environment or when debugging when you forget to start postgres.
Fixes #51

WebHost: Wait for the database to become ready before attempting to run migrations

---

build.cake
src/Athena.Importer/contrib/docker/Dockerfile
src/Athena.Importer/contrib/docker/import.sh
src/Athena/Setup/ApplicationBuilderExtensions.cs

This makes development easier. Instead of:
1. Starting a plain postgres container
2. Starting the API
3. Copying the default admin api key
4. Running the importer
You can now just
1. `docker run -it --rm -p 5432:5432 athenascheduler/db`
:tada:
I've already pushed an image if you want to play around with it without building. It should be automatically built and pushed whenever new commits land on master.

Docker: Make a sample db with test data pre-loaded

---

build.cake

We should probably push the `athenascheduler/db` image when we build it...
Fixes #71

build: Push athenascheduler/db image in push task

---

src/Athena/Setup/ServiceCollectionExtensions.cs
test/Unit/Athena.Importer.Tests/OfferingImporterTests.cs

This fixes the user being bugged by login prompts too frequently. Also, every request now resets the timeout window so if you're actively using the application it shouldn't log you  out anymore.
I also fixed an issue with one of the tests hiding the `Dispose` on a base class.
Fixes #61

Extend login expiry to 1 hour and make it sliding by default

---

src/Athena/Content/js/schedule.js

Suggestion from a fellow student: Make different offerings have different colors to make them easier to distinguish.
Note that his depends on the order they're returned in the database and we're only using 7 colors.

Colorize offerings

---

src/Athena.Core/Repositories/IRequirementRepository.cs
src/Athena.Data/Repositories/RequirementRepository.cs
src/Athena/Content/js/schedule.js
src/Athena/Controllers/api/StudentOfferingsController.cs
src/Athena/Exceptions/BadModelException.cs
src/Athena/Exceptions/OfferingConflictException.cs
src/Athena/Exceptions/UnmetDependencyException.cs
src/Athena/Extensions/EnumerableExtensions.cs
src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
src/Athena/Views/Schedule/ScheduleEditor.cshtml
src/Athena/Views/Schedule/_UnmetDependencyError.cshtml
test/Integration/Athena.Data.Tests/Repositories/RequirementRepositoryTests.cs
test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs

We shouldn't enroll students in courses where they are missing dependent classes. We now show a warning dialog on the scheduler page with a list of direct requirements that are unmet.
Note that we do not follow this chain recursively since we can't easily get requirements of requirements. Personally I think this is fine. There's a potential solution I can think of that involves constructing a graph, finding leaf nodes, and culling nodes when they are completed, but that's non-trivial to implement in the time we have left.
I'm also looking for input on the wording of the dialog, let me know of something doesn't make sense or if things need more clarification. Specifically: Should we make a distinction in the dialog between purely unmet dependencies and unmet dependencies that can be taken …

Prevent students from enrolling in courses with unmet dependencies

---

src/Athena.Core/Exceptions/IllegalPrerequisiteException.cs
src/Athena.Data/Migrations/20180412163557_EnsureConcurrentPrereqsAreNotRegularPrereqs.cs
src/Athena.Data/Migrations/src/20180412163557_EnsureConcurrentPrereqsAreNotRegularPrereqs.sql
src/Athena.Data/Repositories/CourseRepository.cs
test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/MeetingRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/OfferingRepositoryTests.cs
test/Integration/Athena.Data.Tests/Repositories/RequirementRepositoryTests.cs

So this isn't exactly what was going on in #104 listing requirements twice but I know the fix for that and created #105 to fix that. The changes in this PR however definitely need to be made though in case someone ***does*** try to register a requirement as both a prereq and concurrent prereq.
Fixes #102

Prevent courses registering requirements as both prereqs and concurent prereqs

---

src/Athena/Content/js/schedule.js
src/Athena/Extensions/EnumerableExtensions.cs
src/Athena/Views/Schedule/_UnmetDependencyError.cshtml

Previously, unmet dependencies might be duplicated in the warning popup. This fixes that, and adds section headers for unmet prereqs.
Fixes #105

Fix duplicate entries in unmet dependency warnings

---

src/Athena/Content/js/schedule.js

Sorting done client side since I don't think we're technically guaranteed to be in sorted order after serialization.
Fixes #101

Sort meeting dates in scheduler search results

---

.gitignore
README.md
auth-keys.env.sample
docker-compose.yml

We can use this in our presentation. Basically I updated the `docker-compose` sample to pull the official athena image and the sample data db image. It will now read auth keys from an environment file as well. This is all explained in the README.

Update docker-compose example and add documentation for it

---

src/Athena/Extensions/EnumerableExtensions.cs
test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs

Enroll: Exclude offerings with external meetings from conflict checks

---

src/Athena/Content/js/schedule.js

Search results for external / online courses now contain a description explaining why they have no times listed.
Fixes #135

Add descriptions for external courses

---

src/Athena/Setup/ApplicationBuilderExtensions.cs
src/Athena/Setup/ServiceCollectionExtensions.cs
src/Athena/package-lock.json

Getting identity to work behind a proxy is poorly documented. It appears the proxy is checked against a whitelist by default, which only works if you're on `127.0.0.1` or `::1`. Thus, reverse proxy support doesn't work out of the box when running on docker.
Tested on https://athena.nlowe.me
Fixes #164

Fix X-Forwarded-Proto support

---

src/Athena/Content/js/ConfigureCompletedCourses.js
src/Athena/Content/js/schedule.js
src/Athena/Content/js/studentSetup.js
src/Athena/Views/Shared/_Layout.cshtml

Fixes #175.
Extremely heavy-handed, should probably be tweaked later, but `tl;dr` ASP.NET seems to do two different things when the session expires and when the security stamp expires.
* If the user still has a valid browser session, but the security stamp cookie has expired, you get a 403
* If the browser's cookie has expired, you get a 401
This means that there's no way to differentiate between a user not being able to access a resource (403) and a user not being logged in (401) in this check. For the expo, I'm fine with this. Thoughts?

Redirect client side if the user's session expires
