athena-scheduler/athena

src/Athena.Data/Athena.Data.csproj
src/Athena.Data/Extensions/ServiceCollectionExtensions.cs
src/Athena/Athena.csproj
src/Athena/Controllers/HomeController.cs
src/Athena/Exceptions/ApiException.cs
src/Athena/Exceptions/BadModelException.cs
src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
src/Athena/Middleware/SerilogHttpMiddleware.cs
src/Athena/Program.cs
src/Athena/Setup/ApplicationBuilderExtensions.cs
src/Athena/Setup/LoggingConfig.cs
src/Athena/Setup/ServiceCollectionExtensions.cs
src/Athena/Startup.cs

This adds [Serilog](https://serilog.net/) for logging and wires up the database-backed repositories with DI so you can request them in your controllers now. Note that I changed MVC Routing to be entirely attribute-based as I feel it is cleaner and relies on less "magic". If you have any concerns or oppositions to this please let me know and we can discuss.
You will probably need to rebase branches off of master when this gets merged, I can help with that process.

Add logging and basic web host setup

---

src/Athena/Content/css/site.css
src/Athena/Views/Home/Home.cshtml
src/Athena/Views/Shared/_Nav.cshtml

i have altered the hover color that is used for the chip so it appears a different color of blue and has white text. i also added in tool tips for the buttons in the nav-bar.
Fixes #37 
Fixes #38

fixes for nav-bar chip coloring and addition of button tool-tips

---

src/Athena/Views/Home/Home.cshtml
src/Athena/Views/Shared/_CurrentSchedule.cshtml
src/Athena/Views/Shared/_CurrentScheduleModal.cshtml
src/Athena/Views/Shared/_StudentDetails.cshtml

This request will add in a fix for a typo. it also adds in a feature such that the home page shows the information on the user page when the user logs in and it just shows the welcome screen otherwise.
Fixes #32
Fixes #41

the home page has had spelling errors fixed and upon logging in shows profile info

---

src/Athena/Content/css/site.css
src/Athena/Views/Home/Add_Classes.cshtml
src/Athena/Views/Home/Home.cshtml
src/Athena/Views/Home/Schedule_Page.cshtml
src/Athena/Views/Home/User_Page.cshtml
src/Athena/Views/Shared/_CurrentSchedule.cshtml
src/Athena/Views/Shared/_Layout.cshtml
src/Athena/Views/Shared/_StudentDetails.cshtml

I set it up so that the vertical scroll bar will only appear when the user access the page to add classes rather than just having the code in the overall css code.
Fixes #39

vertical scrollbar is now only forced on the add classes page

---

src/Athena/Views/Home/Home.cshtml

i found the issue with the calendar on the home page seemed to come from performing the setup on the tabs after setting up the calendar so i set up the tabs first and now it work. yippe

fixed the times column loading in incorrectly on the home page

---

src/Athena.Core/Repositories/CourseSearchOptions.cs
src/Athena.Core/Repositories/ICourseRepository.cs
src/Athena.Data/Repositories/CourseRepository.cs
src/Athena/Athena.csproj
src/Athena/Content/css/site.css
src/Athena/Content/js/ConfigureCompletedCourses.js
src/Athena/Controllers/StudentController.cs
src/Athena/Controllers/api/StudentCoursesController.cs
src/Athena/Views/Student/ConfigureCompletedCourses.cshtml
src/Athena/Views/Student/Profile.cshtml
src/Athena/package-lock.json
src/Athena/webpack.common.js
test/Integration/Athena.Data.Tests/Repositories/CourseRepositoryTests.cs
test/Unit/Athena.Tests/Controllers/Api/StudentCoursesControllerTests.cs

issue resolved. 
TODO: pagination (#69)
Fixes #31

Mark Courses as Complete or Incomplete from Student Profile

---

src/Athena.Importer/Program.cs

We should probably use the new importer we built if we want any meetings imported...

Fix importer

---

src/Athena/Content/js/studentSetup.js
src/Athena/package-lock.json

I have made it so that the buttons for enrolling/unenrolling and adding and removing programs only show when they are actually needed to be shown to reduce confusion.
Fixes #63

Remove buttons when unneeded

---

src/Athena.Core/Models/Meeting.cs
src/Athena/Content/css/schedule.css
src/Athena/Content/js/schedule.js
src/Athena/Controllers/api/StudentOfferingsController.cs
src/Athena/Exceptions/ApiException.cs
src/Athena/Middleware/CustomErrorHandlerMiddleware.cs
test/Unit/Athena.Tests/Controllers/Api/StudentOfferingsControllerTests.cs

Scheduler: Prevent the student from enrolling in conflicting timeslots

---

src/Athena/Content/js/schedule.js
src/Athena/Views/Home/Home.cshtml
src/Athena/package-lock.json

I have added in the code to make it so that we no longer have the x's available on the classes on the home schedule
fixes #92

home schedule x's removed

---

src/Athena/Views/Student/ConfigureCompletedCourses.cshtml

finish button for Add/drop courses is done and goes to Profile page afterwards
fixes: #89

finish button for add/drop

---

src/Athena.Core/Repositories/ProgramSearchOptions.cs
src/Athena.Data/Repositories/ProgramRepository.cs
src/Athena/Content/js/studentSetup.js
src/Athena/Controllers/api/ProgramController.cs
src/Athena/package-lock.json
test/Integration/Athena.Data.Tests/Repositories/ProgramRepositoryTests.cs
test/Unit/Athena.Tests/Controllers/Api/ProgramControllerTests.cs

On the student setup page, programs now only show for institutions the student has enrolled for, and no longer show up in search results if they're already enrolled.
Fixes #113

Fix searching for programs

---

src/Athena.Importer/data/offering/ecnm151-v401-f2018.json
src/Athena.Importer/data/offering/mthm280-p100-f2018.json
src/Athena.Importer/data/offering/mthm283-p100-s2018.json

test data for meeting ids for ecnm 151-p100
mthm283-p100
mthm280-p100
Fixes: #112

Fixed test data

---

src/Athena/Content/css/footer.css
src/Athena/Content/js/studentSetup.js
src/Athena/Views/Shared/_CurrentSchedule.cshtml

Fixes #121 
Fixes #122
Fixes #124

Minor Style Tweaks

---

src/Athena/Content/css/site.css
src/Athena/Content/js/schedule.js
src/Athena/Models/ScheduleEntry.cs

Attempt to make the scheduler more readable by tweaking titles and tooltips

Make the scheduler more readable by tweaking titles and tooltips

---

src/Athena/Content/js/ConfigureCompletedCourses.js
src/Athena/Content/js/schedule.js
src/Athena/Content/js/studentSetup.js
src/Athena/Content/js/utils.js

Search Results: group in rows of 3

---

src/Athena/Controllers/StudentController.cs

Remove unused route

---

src/Athena/Content/js/schedule.js
src/Athena/Controllers/ScheduleController.cs

Hack-y as hell but it works
Fixes #158

Fix overlay for unmet dependencies

---

src/Athena/Content/css/site.css
src/Athena/Views/Student/Profile.cshtml
src/Athena/Views/Student/_ConfigureCompletedCourses.cshtml

Fix phrasing and scroll issues on profile page

---

src/Athena/Content/css/print.css
src/Athena/Content/css/site.css
src/Athena/Views/Schedule/PrintSchedule.cshtml

it prints in portrait only now
fixes #165

Print in portrait

---

src/Athena/Views/Student/Profile.cshtml

Add save button to profile page and focus search inputs when sections expand

---

src/Athena/Views/Home/Home.cshtml
src/Athena/Views/Shared/_CurrentScheduleModal.cshtml

Fix 'agree' button and wording on front page

---

src/Athena.Importer/data/offering/phyc251-p111-f2018.json
src/Athena.Importer/data/offering/phyc252-p181-f2018.json
src/Athena/Controllers/api/StudentOfferingsController.cs

Fix dep check order and some issues with the test data
